#!/usr/bin/env node
/**
 * Reads every SVG in `icons/`, generates:
 *   - `src/icons/<Name>.tsx` — typed React component (via SVGR)
 *   - `src/icons/index.ts`   — barrel re-export
 *   - `src/registry.ts`      — { name → component } map with JSDoc base64 previews
 *
 * Filename rule: `Icon[_ ]<Words>.svg` → `<Words>` PascalCased (whitespace, `_`, `-` are separators).
 * The base64 preview is embedded only when the optimized SVG is small enough to keep
 * `.d.ts` size sane; oversized icons get a "preview omitted" note instead.
 */
import { readdir, readFile, writeFile, mkdir, rm } from 'node:fs/promises';
import { resolve, basename, extname, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { transform } from '@svgr/core';
import sharp from 'sharp';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const SRC_ICONS = resolve(ROOT, 'icons');
const OUT_ICONS_DIR = resolve(ROOT, 'src/icons');
const REGISTRY_FILE = resolve(ROOT, 'src/registry.ts');

// Each preview is rasterized to a 64×64 PNG so the JSDoc tooltip stays light
// regardless of how heavy the underlying SVG is (some source SVGs are multi-MB
// because they embed raster images).
const PREVIEW_PX = 64;

function toPascalCase(filename) {
  let name = basename(filename, extname(filename));
  name = name.replace(/^Icon[_ ]/i, '');
  return name
    .split(/[\s_-]+/)
    .filter(Boolean)
    .map((p) => p[0].toUpperCase() + p.slice(1))
    .join('');
}

const SVGO_CONFIG = {
  multipass: true,
  plugins: [
    { name: 'preset-default', params: { overrides: { removeViewBox: false } } },
    'prefixIds',
  ],
};

async function main() {
  await rm(OUT_ICONS_DIR, { recursive: true, force: true });
  await mkdir(OUT_ICONS_DIR, { recursive: true });

  const files = (await readdir(SRC_ICONS))
    .filter((f) => f.toLowerCase().endsWith('.svg'))
    .sort();

  const seen = new Map();
  const entries = [];

  for (const file of files) {
    const componentName = toPascalCase(file);
    if (seen.has(componentName)) {
      throw new Error(
        `Name collision: "${file}" and "${seen.get(componentName)}" both → "${componentName}"`,
      );
    }
    seen.set(componentName, file);

    const raw = await readFile(resolve(SRC_ICONS, file), 'utf-8');

    const tsx = await transform(
      raw,
      {
        plugins: ['@svgr/plugin-svgo', '@svgr/plugin-jsx'],
        typescript: true,
        ref: true,
        expandProps: 'end',
        jsxRuntime: 'automatic',
        prettier: false,
        svgo: true,
        svgoConfig: SVGO_CONFIG,
      },
      { componentName },
    );
    await writeFile(resolve(OUT_ICONS_DIR, `${componentName}.tsx`), tsx);

    // Rasterize the SVG to a small PNG thumbnail for the JSDoc preview.
    let preview = null;
    try {
      const pngBuffer = await sharp(Buffer.from(raw), { density: 200 })
        .resize(PREVIEW_PX, PREVIEW_PX, {
          fit: 'contain',
          background: { r: 0, g: 0, b: 0, alpha: 0 },
        })
        .png({ compressionLevel: 9 })
        .toBuffer();
      preview = {
        mime: 'image/png',
        base64: pngBuffer.toString('base64'),
      };
    } catch (err) {
      console.warn(`  preview failed for ${file}: ${err.message}`);
    }

    entries.push({
      name: componentName,
      sourceFile: file,
      preview,
    });
  }

  // src/icons/index.ts — barrel
  const barrel = entries
    .map((e) => `export { default as ${e.name} } from './${e.name}.js';`)
    .join('\n') + '\n';
  await writeFile(resolve(OUT_ICONS_DIR, 'index.ts'), barrel);

  // src/registry.ts — JSDoc-decorated map
  const properties = entries
    .map((e) => {
      const jsdoc = e.preview
        ? `  /**\n   * ![${e.name}](data:${e.preview.mime};base64,${e.preview.base64})\n   *\n   * Source: \`icons/${e.sourceFile}\`\n   */`
        : `  /**\n   * \`${e.name}\` — preview unavailable.\n   *\n   * Source: \`icons/${e.sourceFile}\`\n   */`;
      return `${jsdoc}\n  ${e.name}: Icons.${e.name},`;
    })
    .join('\n');

  const registry = `/* eslint-disable */
// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import * as Icons from './icons/index.js';

/**
 * Registry mapping every Sygnaal icon name to its React component.
 *
 * Each entry carries a JSDoc preview so hovering or autocompleting a
 * \`SygnaalIconName\` value renders the icon inline in your editor.
 */
export const SYGNAAL_ICONS = {
${properties}
} as const;

/** Union of every valid icon name. Hover any value to preview. */
export type SygnaalIconName = keyof typeof SYGNAAL_ICONS;
`;

  await writeFile(REGISTRY_FILE, registry);

  const withPreview = entries.filter((e) => e.preview !== null).length;
  console.log(`Generated ${entries.length} icons → src/icons/`);
  console.log(`  ${withPreview} with preview, ${entries.length - withPreview} without`);
  console.log(`Wrote registry → src/registry.ts`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
